version: '3.7'
services:
    node_service:
        privileged: true
        stdin_open: true
        hostname: vaibhav
        build:
            context: .
            dockerfile: ./Dockerfile
        working_dir: /nodejs
        expose:
            - "8081"
        ports:
            - "8081:8081"
        restart: on-failure
        networks:
            - webnet

networks:
    webnet:
        enable_ipv6: true
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 2001:db8:1::/64